branches:
  - main
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/github"
    - addReleases: top
  - - "@semantic-release/exec"
    - verifyReleaseCmd: ./ci/build-test.sh
      prepareCmd: ./ci/update-versions.sh ${nextRelease.version}
  - - "@semantic-release/git"
    - assets:
        - src/rapids_dependency_file_generator/_version.py
        - src/rapids_dependency_file_generator/schema.json
        - package.json
